;
; File generated by cc65 v 2.16 - Git 18b0aaf
;
	.fopt		compiler,"cc65 v 2.16 - Git 18b0aaf"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_splitXY

; ---------------------------------------------------------------
; void splitXY (unsigned int x, unsigned int y)
;
; A two-directional split in vertical mirroring (horizontal arrangement)
;
; ---------------------------------------------------------------

.segment	"CODE"

; aliases
xval = tmp1
yval = tmp2
xnt = tmp3
magic = tmp4

PPU_STATUS = $2002

.proc	_splitXY: near

.segment	"CODE"

	sta	yval
	jsr	popax
	sta	xval
	txa
	and	#1
	asl	a
	asl	a
	sta	xnt

; precalculate the magic byte
; ((Y & $F8) << 2) | (X >> 3)

	lda	yval
	and	#$f8
	asl	a
	asl	a
	sta	magic

	lda	xval
	lsr	a
	lsr	a
	lsr	a
	ora	magic
	sta	magic

@3:
	bit	PPU_STATUS
	bvs	@3
@4:
	bit	PPU_STATUS
	bvc	@4

; nops here if needed

; action
	lda	xnt
	sta	$2006

	lda	yval
	sta	$2005

	lda	xval
	sta	$2005

	lda	magic
	sta	$2006

	rts
.endproc

